# Generated by Django 3.1 on 2020-08-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=20)),
                ('count_bids', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('actual', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='date comment')),
                ('listing_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionBids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.FloatField()),
                ('user_bid', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='date click')),
                ('listing_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings')),
            ],
        ),
    ]
