# Generated by Django 3.1 on 2020-08-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionbids_auctioncomments_auctionlistings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbids',
            name='listing_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings', to_field='name'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
