# Generated by Django 3.1 on 2020-08-09 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncomments',
            name='listing_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings', to_field='name'),
        ),
        migrations.AlterField(
            model_name='watchlists',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings', to_field='name'),
        ),
    ]
