# Generated by Django 3.1 on 2020-08-10 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200809_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('listing_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings', to_field='name')),
            ],
        ),
    ]
